### ISSUE TITLE
Panic: Send on closed channel

### ISSUE THREAD

**Issue by amirzenoozi** [aler9/gortsplib#25]
Hi,
I Have a little problem when I try to close a connection, in some cases, I will get the below Error: 

```bash
goroutine 9 [running]:
main.main.func1(0x0, 0x0, 0xc00013a800, 0x38, 0x800)
        E:/go-script/rtsp-connect/rtsp-connect.go:35 +0x3d
github.com/aler9/gortsplib.(*clientConnUDPListener).run(0xc000144000)
        C:/Users/*/go/src/github.com/aler9/gortsplib/clientconnudpl.go:88 +0x30c
created by github.com/aler9/gortsplib.(*clientConnUDPListener).start
        C:/Users/*/go/src/github.com/aler9/gortsplib/clientconnudpl.go:60 +0xa5
```

and my code is: 
```go
func gonnaStop(conn *gortsplib.ClientConn, frameThreshold int, frameCount chan int) {
	totalFrame := 0
	for count := range frameCount {
		totalFrame += count
		if totalFrame >= frameThreshold {
			break
		}
	}
	close(frameCount)
	defer conn.Close()
}

func main() {
	// connect to the server and start reading all tracks
	frameThreshold := 1
	conn, err := gortsplib.DialRead("rtsp-link")
	if err != nil {
		panic(err)
	}
	frameCount := make(chan int)
	go gonnaStop(conn, frameThreshold, frameCount)

	err = <-conn.ReadFrames(func(trackID int, typ gortsplib.StreamType, buf []byte) {
		frameCount <- 1
	})
	fmt.Println(err)
}
```

**Comment by aler9** [comment]
Hello, if you want to read 3 RTP/H264 packets and exit, the code is the following

```go

func main() {
	// connect to the server and start reading all tracks
	frameThreshold := 1
	conn, err := gortsplib.DialRead("rtsp-link")
	if err != nil {
		panic(err)
	}
	frameCount := make(chan int)
	go gonnaStop(conn, frameThreshold, frameCount)

        done := make(chan struct{})
        frameCount := 0
	conn.ReadFrames(func(trackID int, typ gortsplib.StreamType, buf []byte) {
		frameCount++
                if frameCount >= 3 {
                    close(done)
                }
	})

        <-done
}
```

But like i wrote in the other issue, you won't get video frames, but encoded RTP/H264 packets, that must be decoded into H264 NALUs, that must be decoded into video frames :)

**Comment by amirzenoozi** [comment]
It Works But When We Put `buf` in a Variable Data is Cropped. 
What Should I Do?
